---
title: "Hauser_Tests_Package"
author: "Emma Hauser"
params:
  today: !r.Sys.Date
output: html_document
---
##Install package

```{r InstallSoilMatrixPackage, echo=T}
devtools::install_github("emhauser/RPackageHW_Hauser/SoilMatrix2/") #This part must be run in the console for the .Rmd to be knit. 
library(SoilMatrix2)
```

##Test for interpolate() function

###Test if interpolate() produces a dataframe with expected number of rows and columns 
```{r interpolate_test, echo=TRUE}
#Since interpolate() requires a dataset, I will perform unit tests using built in R datasets--CO2 and airquality
test <- interpolate(CO2, 4, 95:1000)
expectedrows <- 1000-94
if(nrow(test) == expectedrows)
{
  print("passed")
}else
{
  print("failed")
}
```

##Test for SoilCorMat() function

###Test that the SoilCorMat() function produces the correct correlation coefficients 

```{r SoilCorMat_test, echo=T}
#Since SoilCorMat() requires a dataset, I will perform unit tests using built in R datasets--CO2 and airquality
testCor <- SoilCorMat(CO2, startCol = 4, endCol = 5)
functTestCor <- round(testCor$r[1,2])
actCor <- round(cor(CO2$conc, CO2$uptake))
if(functTestCor == actCor)
{
  print("passed")
} else 
{
  print("failed")
}
```

##Test for plotting functions

###Test that SoilRainbowStats produces correct color spectrum length

```{r PlotTest, echo=T}
#Since SoilRainbowStats() requires a dataset, I will perform unit tests using built in R datasets--CO2 and airquality
#This unit test takes a chunk of code from within the plotting function and determines whether is computes the correct number of colors for the desired color spectrum of the dataset. 
anticipatedNumColors<- nrow(airquality)
calculatedNumColors <-length(rev(colorspace::rainbow_hcl(nrow(airquality))))
if(anticipatedNumColors == calculatedNumColors)
{
  print("passed")
} else 
{
  print("failed")
}

#Also test to ensure that graphs print:
SoilRainbowStats(airquality, 6, 153, 1, 4)

```
